name: Renovate GitHub Actions

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v39.3.3
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
